### ISSUE TITLE
Add a statement to trigger garbage collection in gaml

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama2#69]
**Is your request related to a problem? Please describe.**
For demanding simulations it can be interesting to be able to ask directly in gaml to trigger garbage collection, instead of waiting for all the memory to be filled so gama does it

**Describe the improvement you'd like**
Having a gaml statement that triggers garbage collection, maybe one to get the state of current memory ?

**Describe alternatives you've considered**
Improve gama's overall memory management and garbage collection strategy (which currently doesn't seem good at all) would remove most need for such statement. But in the end there's always going to be edge cases where manually triggering GC could be useful.

**Comment by AlexisDrogoul** [comment]
It is a bad idea to trigger garbage collection manually. We should instead document the cases where the memory is not retrieved correctly, and where relying on Java's strategy (which is the case now) does not work, and see what strategy could be better adapted (maybe using another GC could be tested also). 

But if you really want to dot it, there is already such a statement (actually an action of experiments) called ˋcompact_memory` for this purpose.
